openapi: 3.0.3
info:
  title: Create Contract API
  version: 1.0.0

paths:
  /clients/{proposalId}/create-contract:
    post:
      summary: Create a contract for a given proposal
      parameters:
        - name: proposalId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                costPerHour:
                  type: number
                  format: double
                startDate:
                  type: string
                  format: date
                payment:
                  type: string
                  enum: [PerMilestones, PerProject]
                milestones:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      description:
                        type: string
                      dueDate:
                        type: string
                        format: date
                      expectedHours:
                        type: number
                        format: double
                    required:
                      - title
                      - milestoneNumber
                      - description
                      - dueDate
                      - expectedHours
              required:
                - description
                - costPerHour
                - startDate
                - payment
                - milestones
      responses:
        '200':
          description: Contract created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum: ["true"]
        '404':
          description: Proposal ID not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Proposal ID not found
