openapi: 3.0.3
info:
  title: Contract Conversations API
  version: 1.0.0
paths:
  /api/contracts/{contractId}/contract-conversations:
    get:
      summary: Get contract conversations
      description: Retrieve paginated list of conversations related to a contract
      parameters:
        - name: contractId
          in: path
          required: true
          description: ID of the contract
          schema:
            type: string
            example: 123e4567-e89b-12d3-a456-426614174000
        - name: page
          in: query
          required: false
          description: Page number (starts from 0)
          schema:
            type: integer
            default: 0
            example: 0
        - name: size
          in: query
          required: false
          description: Page size
          schema:
            type: integer
            default: 10
            example: 10
      responses:
        '200':
          description: List of contract conversations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractConversationPageResponse'

    post:
      summary: Create a new contract conversation
      description: Creates a new conversation under a contract
      parameters:
        - name: contractId
          in: path
          required: true
          description: ID of the contract
          schema:
            type: string
            example: 123e4567-e89b-12d3-a456-426614174000
        - name: content
          in: query
          required: true
          description: Conversation text content
          schema:
            type: string
            example: This is a new conversation message
      responses:
        '200':
          description: Conversation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

components:
  schemas:
    ContractConversationPageResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ContractConversation'
        pageable:
          type: object
          properties:
            pageNumber:
              type: integer
              example: 0
            pageSize:
              type: integer
              example: 5
            sort:
              type: object
              properties:
                empty:
                  type: boolean
                  example: true
                unsorted:
                  type: boolean
                  example: true
                sorted:
                  type: boolean
                  example: false
            offset:
              type: integer
              example: 0
            unpaged:
              type: boolean
              example: false
            paged:
              type: boolean
              example: true
        last:
          type: boolean
          example: true
        totalElements:
          type: integer
          example: 2
        totalPages:
          type: integer
          example: 1
        size:
          type: integer
          example: 5
        number:
          type: integer
          example: 0
        sort:
          type: object
          properties:
            empty:
              type: boolean
              example: true
            unsorted:
              type: boolean
              example: true
            sorted:
              type: boolean
              example: false
        numberOfElements:
          type: integer
          example: 2
        first:
          type: boolean
          example: true
        empty:
          type: boolean
          example: false

    ContractConversation:
      type: object
      properties:
        convoId:
          type: string
          example: dd882809-6399-4d72-a340-cd61381356ba
        convoOwner:
          $ref: '#/components/schemas/User'
        content:
          type: string
          example: Second convo test
        date:
          type: string
          format: date-time
          example: 2025-05-10T14:28:41.719+00:00

    User:
      type: object
      properties:
        profilePicture:
          type: string
          example: https://res.cloudinary.com/dhfb7i5h1/image/upload/v1740614334/freelancers_profile_pictures/ii1qf658zpi5f2tiwhby.png
        name:
          type: string
          example: client01
        role:
          type: string
          example: CLIENT
        id:
          type: string
          example: f352fd81-02d0-41e3-a8da-ee9323eac681

    SimpleResponse:
      type: object
      properties:
        message:
          type: string
          example: Contract Convo Created!
