openapi: 3.0.0
info:
  title: Freelancer Contract API
  version: 1.0.0
paths:
  /freelancers/my-contracts/{id}:
    get:
      summary: Get details of a specific contract for a freelancer
      description: Retrieves detailed information about a specific contract including status, job details, client info.
      operationId: getMyContractById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the contract to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Successful response with contract details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contract"
        "401":
          description: Unauthorized - Invalid or missing token
        "404":
          description: Contract not found

  /freelancers/my-contracts/{id}/milestones:
    get:
      summary: Get milestones of a specific contract
      description: Retrieves the list of milestones for a specific contract with pagination.
      operationId: getMyContractMilestones
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the contract to retrieve milestones for
          schema:
            type: string
        - name: page
          in: query
          required: true
          description: The page number for paginated results (0-based, defaults to 0)
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: size
          in: query
          required: true
          description: The number of items per page (defaults to 10)
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: Successful response with milestones details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageMilestone"
        "401":
          description: Unauthorized - Invalid or missing token
        "404":
          description: Contract or milestones not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Contract:
      type: object
      required:
        - contractStatus
        - jobId
        - clientName
        - profilePic
        - pricePerHour
        - startDate
        - endDate
        - jobTitle
        - projectType
        - totalCurrentEarnings
        - hoursWorked
      properties:
        contractStatus:
          type: string
          enum: [active, ended]
          description: Current status of the contract
        jobId:
          type: string
          description: ID of the job associated with the contract
        jobTitle:
          type: string
          description: Title of the job associated with the contract
        clientName:
          type: string
          description: Name of the client
        clientProfilePic:
          type: string
          format: uri
          description: URL to the client's profile picture
        freelancerName:
          type: string
          description: Name of the freelancer
        freelancerProfilePic:
          type: string
          format: uri
          description: URL to the freelancer's profile picture
        pricePerHour:
          type: number
          format: float
          description: Hourly rate for the contract
        totalCurrentEarnings:
          type: number
          format: float
          description: Total earnings accumulated for the contract so far
        hoursWorked:
          type: number
          format: float
          description: Total hours worked on the contract to date
        startDate:
          type: string
          format: date
          description: Date when the contract started
        endDate:
          type: string
          description: Date when the contract ended or "present" if still active
        isCommunity:
          type: boolean
          description: If the freelancer is part of a community
        projectType:
          type: string
          enum: [PerMilestones, PerProject]
          description: Type of project billing structure (Per Milestones or Per Project)

    PageMilestone:
      type: object
      required:
        - content
        - totalElements
        - totalPages
        - size
        - number
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/Milestone"
        pageable:
          type: object
          properties:
            sort:
              type: object
              properties:
                unsorted:
                  type: boolean
                  description: Whether the results are unsorted
                sorted:
                  type: boolean
                  description: Whether the results are sorted
                empty:
                  type: boolean
                  description: Whether the sort field is empty
            pageNumber:
              type: integer
              format: int32
              description: The current page number (0-based index)
            pageSize:
              type: integer
              format: int32
              description: The number of items per page
            offset:
              type: integer
              format: int32
              description: The offset of the current page
            unpaged:
              type: boolean
              description: Whether the page is unpaged
        totalElements:
          type: integer
          format: int32
          description: The total number of `worksDone` items
        totalPages:
          type: integer
          format: int32
          description: The total number of pages available
        size:
          type: integer
          format: int32
          description: The size of the current page (items per page)
        number:
          type: integer
          format: int32
          description: The current page number (starts at 0)
          

    Milestone:
      type: object
      required:
        - title
        - description
        - expectedHours
        - dueDate
        - status
        - milestoneId
      properties:
        title:
          type: string
          description: Title of the milestone
        description:
          type: string
          description: Description of the milestone
        expectedHours:
          type: number
          description: Expected hours to complete the milestone
        dueDate:
          type: string
          format: date
          description: Due date for the milestone
        status:
          type: string
          enum: [not_started, in_review, in_progress, approved]
          description: Current status of the milestone
        milestoneId:
          type: string
          description: Unique identifier for the milestone
