openapi: 3.0.0
info:
  title: Finance API
  version: 1.0.0
tags:
  - name: Finance
    description: API for financial transactions and profiles
paths:
  /api/finance/transactions:
    post:
      summary: Get financial transactions
      tags:
        - Finance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate:
                  type: string
                  format: date
                  description: Start date for transactions
                endDate:
                  type: string
                  format: date
                  description: End date for transactions
                page:
                  type: integer
                  example: 1
                size:
                  type: integer
                  example: 10
                type:
                  type: string
                  enum: [ TRANSACTION , DEPOSIT , WITHDRAWL]
      responses:
        '200':
          description: A paginated list of financial transactions
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "30132123"
                        date:
                          type: string
                          format: date
                          example: "16/10/2024"
                        type:
                          type: string
                          enum: [ TRANSACTION , DEPOSIT , WITHDRAWL]
                          example: "TRANSACTION"
                        description:
                          type: string
                          example: "Project payment from [Client Name]"
                        amount:
                          type: number
                          example: 562
                        contractId:
                          type: string
                  pageable:
                    type: object
                    properties:
                      pageNumber:
                        type: integer
                        example: 1
                      pageSize:
                        type: integer
                        example: 10
                      totalElements:
                        type: integer
                        example: 100
                      totalPages:
                        type: integer
                        example: 10
                      last:
                        type: boolean
                        example: false
      
  /api/finance/profile:
    get:
      summary: Get user finance profile
      tags:
        - Finance
      responses:
        '200':
          description: Finance profile details
          content:
            application/json:
              schema:
                type: object
                properties:
                  profilePicture:
                    type: string
                    format: uri
                    example: "https://example.com/images/isabel-austin.jpg"
                  name:
                    type: string
                    example: "Isabel Austin"
                  totalBalance:
                    type: number
                    example: 1000
                  restrictedOrWorkInProgressBalance:
                    type: number
                    example: 1000
