openapi: 3.0.0
info:
  title: Community API
  version: 1.0.0

paths:
  /communities/{communityId}/profile:
    get:
      summary: Get community profile
      security:
        - bearerAuth: []
      parameters:
        - name: communityId
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  profilePicture:
                    type: string
                  coverPhoto:
                    type: string
                  title:
                    type: string
                  name:
                    type: string
                  country:
                    type: string
                  pricePerHour:
                    type: number
                  rate:
                    type: number
                    minimum: 0
                    maximum: 5
                  skills:
                    type: array
                    items:
                      type: string
                  description:
                    type: string
                  members:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        position:
                          type: string
                        freelancerId:
                          type: string
                        freelancerProfilePicture:
                          type: string
                  isFull:
                    type: boolean
                  isMember:
                    type: boolean
                  isAdmin:
                    type: boolean
                  experienceLevel:
                    type: string
                    enum:
                      - entry_level
                      - intermediate
                      - expert
                  avgHoursPerWeek:
                    type: number

  /communities/{id}/workdone:
    get:
      summary: Get work done for a community
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
        - name: page
          in: query
          required: false
          description: The page number for pagination
          schema:
            type: integer
            minimum: 0
        - name: size
          in: query
          required: false
          description: The number of items per page
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Successfully retrieved the paginated list of works done
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageableWorksDone"

  /communities/{id}/profile-picture:
    patch:
      summary: Update the community's profile picture (Admin only)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      description: Upload a new profile picture for a community. Only admins can perform this action.
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ProfilePictureUploadRequest"
      responses:
        "403":
          description: Forbidden – Only community admins can update this resource.

  /communities/{id}/cover-picture:
    patch:
      summary: Update the community's cover picture (Admin only)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      description: Upload a new cover picture for a community. Only admins can perform this action.
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CoverPictureUploadRequest"
      responses:
        "403":
          description: Forbidden – Only community admins can update this resource.

  /communities/{id}/skills:
    patch:
      summary: Update the community's skills (Admin only)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      description: Update the skills associated with a community. Only admins can perform this action.
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSkillsRequest"
      responses:
        "403":
          description: Forbidden – Only community admins can update this resource.

  /communities/{id}/description:
    patch:
      summary: Update the community's description (Admin only)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      description: Update the description of a community. Only admins can perform this action.
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDescriptionRequest"
      responses:
        "403":
          description: Forbidden – Only community admins can update this resource.

  /communities/{id}/header-section:
    patch:
      summary: Update the community's header section (Admin only)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      description: Update the community's name, job title, country, and price per hour. Only admins can perform this action.
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateHeaderSectionRequest"
      responses:
        "403":
          description: Forbidden – Only community admins can update this resource.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PageableWorksDone:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/WorkDone"
          description: List of works done in the current page
        pageable:
          type: object
          properties:
            sort:
              type: object
              properties:
                unsorted:
                  type: boolean
                  description: Whether the results are unsorted
                sorted:
                  type: boolean
                  description: Whether the results are sorted
                empty:
                  type: boolean
                  description: Whether the sort field is empty
            pageNumber:
              type: integer
              format: int32
              description: The current page number (0-based index)
            pageSize:
              type: integer
              format: int32
              description: The number of items per page
            offset:
              type: integer
              format: int32
              description: The offset of the current page
            unpaged:
              type: boolean
              description: Whether the page is unpaged
        totalElements:
          type: integer
          format: int32
          description: The total number of `worksDone` items
        totalPages:
          type: integer
          format: int32
          description: The total number of pages available
        size:
          type: integer
          format: int32
          description: The size of the current page (items per page)
        number:
          type: integer
          format: int32
          description: The current page number (starts at 0)

    WorkDone:
      type: object
      properties:
        jobName:
          type: string
          description: Name of the job completed
        jobId:
          type: string
          description: Name of the job completed
        rate:
          type: number
          format: float
          description: Rating given by the client after finishing the job
          minimum: 0
          maximum: 5
        pricePerHour:
          type: number
          format: float
          description: Hourly rate charged for this job
        totalHours:
          type: number
          format: float
          description: Total hours worked on this job

    UpdateHeaderSectionRequest:
      type: object
      properties:
        firstName:
          type: string
          description: The community's name.
        jobTitle:
          type: string
          description: The main job title or focus of the community.
        avgHoursPerWeek:
          type: number
          description: Updated average hours per week.
        pricePerHour:
          type: number
          format: float
          description: Updated hourly rate.
      required:
        - name
        - jobTitle
        - avgHoursPerWeek
        - pricePerHour

    ProfilePictureUploadRequest:
      type: object
      properties:
        profilePicture:
          type: string
          format: binary
          description: The profile picture file to upload (JPEG, PNG, or WEBP).

    CoverPictureUploadRequest:
      type: object
      properties:
        coverPicture:
          type: string
          format: binary
          description: The cover picture file to upload (JPEG, PNG, or WEBP).

    UpdateSkillsRequest:
      type: object
      properties:
        skills:
          type: array
          items:
            type: string
          description: Updated list of skills.
      required:
        - skills

    UpdateDescriptionRequest:
      type: object
      properties:
        description:
          type: string
          description: Updated community description.
      required:
        - description
