openapi: 3.0.0
info:
  title: Freelancers Communities API
  version: "1.0"
paths:
  /freelancers/communities/{communityId}/posts:
    get:
      summary: Get paginated list of posts for a specific community
      description: |
        Retrieves a paginated list of posts belonging to the specified community.
        The page and size parameters are used to control pagination.
      parameters:
        - in: path
          name: communityId
          required: true
          schema:
            type: string
          description: ID of the community
        - in: query
          name: page
          description: The page number to retrieve
          required: false
          schema:
            type: integer
            minimum: 0
        - in: query
          name: size
          description: The number of records per page
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Paginated response with posts data
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: "#/components/schemas/Post"
                  totalElements:
                    type: integer
                    description: The total number of elements
                  totalPages:
                    type: integer
                    description: The total number of pages
                  number:
                    type: integer
                    description: The current page number
                  size:
                    type: integer
                    description: The size of the page
        "401":
          description: Unauthorized - Invalid or missing JWT token

  /freelancers/communities/{communityId}/post/{postId}/post-comments:
    get:
      summary: Get paginated list of comments for a specific post
      description: |
        Retrieves a paginated list of comments belonging to the specified post.
        The page and size parameters are used to control pagination.
      parameters:
        - in: path
          name: communityId
          required: true
          schema:
            type: string
          description: ID of the community
        - in: path
          name: postId
          required: true
          schema:
            type: string
          description: ID of the post
        - in: query
          name: page
          description: The page number to retrieve
          required: false
          schema:
            type: integer
            minimum: 0
        - in: query
          name: size
          description: The number of records per page
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Paginated response with post comments
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: "#/components/schemas/Comment"
                  totalElements:
                    type: integer
                    description: The total number of elements
                  totalPages:
                    type: integer
                    description: The total number of pages
                  number:
                    type: integer
                    description: The current page number
                  size:
                    type: integer
                    description: The size of the page
        "401":
          description: Unauthorized - Invalid or missing JWT token

  /freelancers/communities/{communityId}/post:
    post:
      summary: Create a new post in a specific community
      description: |
        Creates a new post within the given community.
        Requires a valid JWT token and membership in the community.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: communityId
          required: true
          schema:
            type: string
          description: ID of the community
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePostRequest"
      responses:
        "201":
          description: Post created successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized - Invalid or missing JWT token

  /freelancers/communities/{communityId}/posts/{postId}/comment:
    post:
      summary: Add a comment to a post in a specific community
      description: |
        Creates a new comment on a post within the given community.
        Requires a valid JWT token and membership in the community.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: communityId
          required: true
          schema:
            type: string
          description: ID of the community
        - in: path
          name: postId
          required: true
          schema:
            type: string
          description: ID of the post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: Content of the new comment
              required:
                - content
      responses:
        "201":
          description: Comment created successfully
        "400":
          description: Bad request
        "401":
          description: Unauthorized - Invalid or missing JWT token

  /freelancers/communities/{communityId}/post/{postId}/likes:
    get:
      summary: Get list of freelancers who liked a post
      description: Retrieves a list of freelancers who liked the specified post, including their ID, name, and profile picture.
      operationId: getPostLikes
      parameters:
        - name: communityId
          in: path
          description: Unique identifier of the community
          required: true
          schema:
            type: string
        - name: postId
          in: path
          description: Unique identifier of the post
          required: true
          schema:
            type: string

      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response with list of freelancers who liked the post
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostLikesResponse"
        "400":
          description: Invalid postId format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Post not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /freelancers/communities/{communityId}/post/{postId}/likes/{liked}:
    post:
      summary: Like or unlike a post
      description: Allows an authenticated freelancer to like or unlike a post based on the liked parameter.
      operationId: likePost
      parameters:
        - name: communityId
          in: path
          description: Unique identifier of the community
          required: true
          schema:
            type: string
        - name: postId
          in: path
          description: Unique identifier of the post
          required: true
          schema:
            type: string
        - name: liked
          in: path
          description: Set to true to like the post, false to unlike it
          required: true
          schema:
            type: boolean
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Action completed successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Invalid postId or liked parameter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Post not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Conflict (e.g., post already liked)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # ---- Post Data ----
    Post:
      type: object
      properties:
        postID:
          type: string
          description: Unique identifier of the post
        postOwner:
          type: object
          properties:
            freelancerName:
              type: string
              description: Name of the freelancer who owns the post
            profilePicture:
              type: string
              description: URL/base64 string for the freelancer's profile picture
            freelancerId:
              type: string
              description: Unique identifier of the freelancer
          required:
            - freelancerName
            - freelancerId
        postTitle:
          type: string
          description: Title of the post
        postContent:
          type: string
          description: Main content of the post
        isLiked:
          type: boolean
          description: Indicates if the current user has liked the post
        numberOfLikes:
          type: integer
          description: Total number of likes on the post
        numberOfComments:
          type: integer
          description: Total number of comments on the post
        date:
          type: string
          format: date-time
          description: Date and time the post was created or published
      required:
        - postID
        - postOwner
        - postTitle
        - postContent
        - isLiked
        - numberOfLikes
        - numberOfComments
        - date

    # ---- Comment Data ----
    Comment:
      type: object
      properties:
        postOwner:
          type: object
          properties:
            freelancerName:
              type: string
              description: Name of the freelancer who owns the comment
            profilePicture:
              type: string
              description: URL/base64 string for the freelancer's profile picture
            freelancerId:
              type: string
              description: Unique identifier of the freelancer
          required:
            - freelancerName
            - freelancerId
        date:
          type: string
          format: date-time
          description: Date and time the comment was created
        commentId:
          type: string
          description: Unique identifier for the comment
        content:
          type: string
          description: Content of the comment
      required:
        - postOwner
        - date
        - commentId
        - content

    # ---- Create Post Request Body ----
    CreatePostRequest:
      type: object
      properties:
        postTitle:
          type: string
          description: Title of the new post
        postContent:
          type: string
          description: Content of the new post
      required:
        - postTitle
        - postContent
    Freelancer:
      type: object
      properties:
        freelancerId:
          type: string
          description: Unique identifier of the freelancer
        freelancerName:
          type: string
          description: Name of the freelancer
        profilePic:
          type: string
          description: URL to the freelancer's profile picture
          nullable: true
      required:
        - freelancerId
        - freelancerName
    PostLikesResponse:
      type: object
      properties:
        likes:
          type: array
          items:
            $ref: "#/components/schemas/Freelancer"

      required:
        - likes

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: Success message (e.g., "Post liked successfully")
      required:
        - message
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Description of the error
      required:
        - error
