openapi: 3.0.0
info:
  title: Community API
  version: 1.0.0
paths:
  /communities/{communityId}/profile:
    get:
      summary: Get community profile
      security:
        - bearerAuth: []
      parameters:
        - name: communityId
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  profilePicture:
                    type: string
                  coverPhoto:
                    type: string
                  title:
                    type: string
                  name:
                    type: string
                  country:
                    type: string
                  pricePerHour:
                    type: number
                  rate:
                    type: number
                    minimum: 0
                    maximum: 5
                  skills:
                    type: array
                    items:
                      type: string
                  description:
                    type: string
                  members:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        position:
                          type: string
                  isFull:
                    type: boolean
                  isMember:
                    type: boolean
                  isAdmin:
                    type: boolean

  /communities/{id}/workdone:
    get:
      summary: Get work done for a community
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
        - name: page
          in: query
          required: false
          description: The page number for pagination
          schema:
            type: integer
            minimum: 0
        - name: size
          in: query
          required: false
          description: The number of items per page
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: A page of work done
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      type: object
                      properties:
                        jobName:
                          type: string
                        jobId:
                          type: string
                        rate:
                          type: integer
                          minimum: 0
                          maximum: 5
                        pricePerHour:
                          type: number
                        totalHours:
                          type: integer
                  totalElements:
                    type: integer
                  totalPages:
                    type: integer
                  size:
                    type: integer
                  number:
                    type: integer

  /communities/{id}/profile-picture:
    patch:
      summary: Update the community's profile picture (Admin only)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      description: Upload a new profile picture for a community. Only admins can perform this action.
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProfilePictureUploadRequest'
      responses:
        "403":
          description: Forbidden – Only community admins can update this resource.
  
  /communities/{id}/cover-picture:
    patch:
      summary: Update the community's cover picture (Admin only)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      description: Upload a new cover picture for a community. Only admins can perform this action.
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CoverPictureUploadRequest'
      responses:
        "403":
          description: Forbidden – Only community admins can update this resource.

  /communities/{id}/skills:
    patch:
      summary: Update the community's skills (Admin only)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      description: Update the skills associated with a community. Only admins can perform this action.
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSkillsRequest'
      responses:
        "403":
          description: Forbidden – Only community admins can update this resource.

  /communities/{id}/description:
    patch:
      summary: Update the community's description (Admin only)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      description: Update the description of a community. Only admins can perform this action.
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDescriptionRequest'
      responses:
        "403":
          description: Forbidden – Only community admins can update this resource.

  /communities/{id}/header-section:
    patch:
      summary: Update the community's header section (Admin only)
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the community
          schema:
            type: string
      description: Update the community's name, job title, country, and price per hour. Only admins can perform this action.
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateHeaderSectionRequest'
      responses:
        "403":
          description: Forbidden – Only community admins can update this resource.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UpdateHeaderSectionRequest:
      type: object
      properties:
        name:
          type: string
          description: The community's name.
        jobTitle:
          type: string
          description: The main job title or focus of the community.
        country:
          type: string
          description: Updated country of operation.
        pricePerHour:
          type: number
          format: float
          description: Updated hourly rate.
      required:
        - name
        - jobTitle
        - country
        - pricePerHour
        
    ProfilePictureUploadRequest:
      type: object
      properties:
        profilePicture:
          type: string
          format: binary
          description: The profile picture file to upload (JPEG, PNG, or WEBP).
  
    CoverPictureUploadRequest:
      type: object
      properties:
        coverPicture:
          type: string
          format: binary
          description: The cover picture file to upload (JPEG, PNG, or WEBP).
    
    UpdateSkillsRequest:
      type: object
      properties:
        skills:
          type: array
          items:
            type: string
          description: Updated list of skills.
      required:
        - skills
    
    UpdateDescriptionRequest:
      type: object
      properties:
        description:
          type: string
          description: Updated community description.
      required:
        - description
