openapi: 3.0.0
info:
  title: Freelancer Jobs API
  version: 1.0.0
  description: API to retrieve freelancer job details by job ID.
servers:
  - url: http://localhost:3000
paths:
  /freelancers/jobs/{id}:
    get:
      summary: Get Freelancer Job Details
      description: >
        Retrieves the details of a freelancer job by its ID.
        
      parameters:
        - name: id
          in: path
          description: Unique identifier for the job.
          required: true
          schema:
            type: string
        
      responses:
        "200":
          description: Job details retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  projectTitle:
                    type: string
                    description: The title of the project.
                  postedAt:
                    type: string
                    format: date-time
                    description: The date and time when the job was posted.
                  projectDescription:
                    type: string
                    description: A detailed description of the project.
                  canApply:
                    type: boolean
                    description: A detailed description of the project
                  
                  projectLength:
                    type: string
                    description: The expected duration or length of the project.
                    enum:
                      - _less_than_1_month
                      - _1_to_3_months
                      - _3_to_6_months
                      - _more_than_6_months
                  experienceLevel:
                    type: string
                    description: The required experience level.
                    enum:
                      - entry_level
                      - intermediate
                      - expert
                  expectedPricePerHour:
                    type: string
                    description: The expected hourly payment rate.
                  skills:
                    type: array
                    description: List of required skills.
                    items:
                      type: string
                  client:
                    type: object
                    description: Details of the client who posted the job.
                    properties:
                      completedJobs:
                        type: integer
                        description: The total number of completed jobs by the client.
                      totalSpent:
                        type: string
                        description: The total amount spent by the client.
                      rate:
                        type: number
                        description: The client's rating.
                  message:
                    type: string
                    description: A response message.
                  type:
                    type: string
                    description: The response type.
              examples:
                valid:
                  summary: Valid job details
                  value:
                    projectTitle: "Modern UI/UX Design for Mobile App"
                    postedAt: "2023-10-04T12:34:56Z"
                    projectDescription: "Design a cutting-edge mobile interface with an emphasis on user experience."
                    projectLength: "_1_to_3_months"
                    experienceLevel: "intermediate"
                    expectedPricePerHour: "$25"
                    canApply : true
                    skills: ["UI Design", "UX Design", "Figma", "Adobe XD"]
                    client:
                      completedJobs: 150
                      totalSpent: "$7500"
                      rate: 4.8

        "404":
          description: Job not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The HTTP status (e.g., "404 NOT_FOUND").
                  message:
                    type: string
                    description: Error message indicating the job was not found.
                  timStamp:
                    type: number
                    description: Unix timestamp or epoch milliseconds when the error occurred.
                  Type:
                    type: string
                    description: The error type (e.g., "NOT_FOUND").
              examples:
                jobNotFound:
                  summary: Invalid job ID
                  value:
                    status: "404 NOT_FOUND"
                    message: "Job not found."
                    timStamp: 1693662310
                    Type: "NOT_FOUND"
