openapi: "3.0.0"
info:
  title: Job Application API
  version: "1.0.0"
  description: API for submitting job applications and retrieving freelancer communities. Requires authentication.

servers:
  - url: http://localhost/

paths:
  /freelancers/proposals/{jobid}:
    parameters:
      - name: jobid
        in: path
        required: true
        description: Dynamic identifier for the job.
        schema:
          type: string
    post:
      summary: Submit a job application
      description: Create a new job application with job identifier, freelancer payment details, milestones, cover letter, and attachments.
      security:
        - bearerAuth: []
      requestBody:
        description: Job application details payload
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JobApplication"
            example:
              jobId: "job-001"
              candidateId: "candidate-123"
              pricePerHour: 50.00
              freelancerPayment: PerMilestones
              milestones:
                - milestoneNumber: 1
                  title: "Design Phase"
                  description: "Complete the initial design mockups."
                  dueDate: "2025-03-01"
                  expectedHours: 20
                - milestoneNumber: 2
                  title: "Development Phase"
                  description: "Develop the main features."
                  dueDate: "2025-04-15"
                  expectedHours: 40
              coverLetter: "I am very interested in this job and believe my skills are a perfect match."
              attachments:
                - "http://example.com/project.pdf"
      responses:
        "201":
          description: Application successfully submitted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobApplicationResponse"
              example:
                type: "successful"
                message: "Job application submitted successfully."
        "400":
          description: Invalid input provided
        "401":
          description: Unauthorized request

  /freelancers/owned-communities:
    get:
      summary: Get communities where the freelancer is the leader
      description: Retrieves the list of communities led by a specific freelancer. NOTE -> the first element of the array is always the freelancer.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response with a list of communities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "12345"
                    name:
                      type: string
                      example: "Tech Innovators"
        "401":
          description: Unauthorized - Invalid or missing token
        "404":
          description: Freelancer not found or has no communities

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    JobApplication:
      type: object
      required:
        - jobId
        - candidateId
        - pricePerHour
        - freelancerPayment
        - coverLetter
        - milestones
      properties:
        jobId:
          type: string
          description: Identifier of the job for which the application is submitted.
        candidateId:
          type: string
          description: Identifier of the candidate submitting the application.
        pricePerHour:
          type: number
          format: double
          description: Hourly rate for the freelancer.
        freelancerPayment:
          type: string
          enum: [PerMilestones, PerProject]
          description: >
            Indicates how the freelancer is paid. Use "PerMilestones" if payment is divided into multiple milestones,
            or "PerProject" for a one-time payment.
        milestones:
          type: array
          items:
            $ref: "#/components/schemas/Milestone"
        coverLetter:
          type: string
          description: Cover letter accompanying the job application.
        attachments:
          type: array
          items:
            type: string
            format: uri
    Milestone:
      type: object
      required:
        - milestoneNumber
        - title
        - description
        - dueDate
        - expectedHours
      properties:
        milestoneNumber:
          type: integer
          description: Sequential number of the milestone in the project.
        title:
          type: string
          description: Title of the milestone.
        description:
          type: string
          description: Detailed description of the milestone.
        dueDate:
          type: string
          format: date
          description: Due date for the milestone (YYYY-MM-DD).
        expectedHours:
          type: number
          format: double
          description: Expected number of hours for the milestone.
    JobApplicationResponse:
      type: object
      properties:
        type:
          type: string
          description: Unique identifier for the submitted job application.
        message:
          type: string
          description: A confirmation message.
    Error:
      type: object
      additionalProperties: false
      properties:
        type:
          type: string
          description: Error type.
        message:
          type: string
          description: Detailed error message.
