openapi: 3.0.0
info:
  title: Freelancer Jobs API
  version: 1.0.0
  description: API to retrieve freelancer job details by job ID.
servers:
  - url: http://localhost:3000
paths:
  /jobs/{id}:
    get:
      summary: Get Freelancer Job Details
      description: >
        Retrieves the details of a freelancer job by its ID.
        
      parameters:
        - name: id
          in: path
          description: Unique identifier for the job.
          required: true
          schema:
            type: string
        
      responses:
        "200":
          description: Job details retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  projectTitle:
                    type: string
                    description: The title of the project.
                  postedAt:
                    type: string
                    format: date-time
                    description: The date and time when the job was posted.
                  projectDescription:
                    type: string
                    description: A detailed description of the project.
                  projectLength:
                    type: string
                    description: The expected duration or length of the project.
                  experienceLevel:
                    type: string
                    description: The required experience level.
                  hourlyRange:
                    type: string
                    description: The hourly payment range.
                  listOfSkills:
                    type: array
                    description: List of required skills.
                    items:
                      type: string
                  message:
                    type: string
                    description: A response message.
                  type:
                    type: string
                    description: The response type.
              examples:
                valid:
                  summary: Valid job details
                  value:
                    projectTitle: "Modern UI/UX Design for Mobile App"
                    postedAt: "2023-10-04T12:34:56Z"
                    projectDescription: "Design a cutting-edge mobile interface with an emphasis on user experience."
                    projectLength: "3 months"
                    experienceLevel: "Intermediate"
                    hourlyRange: "$25"
                    skills: ["UI Design", "UX Design", "Figma", "Adobe XD"]

        "404":
          description: Job not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating the job was not found.
                  type:
                    type: string
                    description: The error type.
              examples:
                jobNotFound:
                  summary: Invalid job id
                  value:
                    message: "Job not found."
                    type: "notFound"
